### ISSUE TITLE
Don't enable matrix by default

### ISSUE THREAD

**Issue by provokateurin** [UnifiedPush/common-proxies#49]
Matrix is enabled by default, I'd expect everything to be disabled by default and then I only need to enable the stuff I actually want to run. Right now I have to manually disable matrix.

**Comment by karmanyaahm** [comment]
I originally enabled matrix by default because 1. it doesn't require any configuration, 2. if you don't set that path in your reverse proxy, it won't do anything, anyways.

Now, I too think it would've been better to leave it disabled (given the proliferation of native matrix gateways and other uses of common proxies); but, there's no way to do it while maintaining backwards compatibility, not breaking people's existing configurations.

So I can't do this until 2.0, sorry.
